/// CAPEXP Association Task
/// 3 November 2019


var shuffleSequence = seq(
                          "setcounter", // set counter immediately to start next Latin square list
                          "Welcome",
                          "Consent",
                          "Instructions01",
                          sepWith("sep",
                              seq("practice")),
                          "Instructions02",
                          sepWith("sep",
                               rshuffle(anyOf(
                                    "V_r", "V_u"))),
                          "sr",
                          "Outro",
                          "Close"
                          );

var showProgressBar =        true;
var progressBarText =        "Fortschritt";
var continueMessage =        "Hier klicken um fortzufahren.";
var manualSendResults =      true;
var sendingResultsMessage =  "Die Ergebnisse werden an den Server gesendet.";
var completionMessage =      "Die Ergebnisse wurden erfolgreich an den Server gesendet. Sie erhalten nun den Prolific-Completion Code";


var defaults = [
    "Form",{continueMessage:"Hier klicken um fortzufahren."},
    "Message",{continueMessage:"Hier klicken um fortzufahren."},
    "Question",{
        as: [
                [1,"1"],
                [2,"2"],
                [3,"3"],
                [4,"4"],
                [5,"5"],
                [6,"6"],
                [7,"7"]
            ],
        presentAsScale: true,
        leftComment: "nicht plausibel",
        rightComment: "sehr plausibel"}
];


var items =[
    ["setcounter", "__SetCounter__", {  }],

    [ "Welcome",
      "Form",
      {"html": {include: "Welcome.html" }}
    ],

    [ "Consent",
      "Form",
      {"html": {include: "Consent.html" }}
    ],

    [ "Instructions01",
      "Form",
      {"html": {include: "Instructions01.html" }}
    ],

    [ "Instructions02",
      "Form",
      {"html": {include: "Instructions02.html" }}
    ],

    [ "Outro",
      "Form",
      {"html": {include: "Outro.html" }}
    ],

    [ "Close",
      "Message",
      { html: "Sie können das Fenster jetzt schließen.", transfer: null}
    ],

    [ "sep",
      "Separator",
      {transfer: 500, normalMessage:""}
    ],

	["sr", "__SendResults__", { }],


  ["practice", 'Question',{q:'Ludmilla verließ die Universität  -  Sofort ging sie in die Vorlesung '}],
  ["practice", 'Question',{q:'Urs bezahlte die Studiengebühren   -   Danach bekam er einen Exmatrikulationsbescheid '}],
  ["practice", 'Question',{q:'Torsten steigt aus dem Swimmingpool  -  Sofort trocknete er sich mit dem Handtuch '}],
  ["practice", 'Question',{q:'Francesca kocht Spaghetti  -  Später nimmt sie das Sieb '}],
  ["practice", 'Question',{q:'Alena bereitet ihr Referat vor  -  Schnell kommt sie unter Zeitdruck  '}],
  ["practice", 'Question',{q:'Xenia geht aus dem Haus  -  Schnell schlüppft sie in ihre Pantoffeln   '}],
  ["practice", 'Question',{q:'Mariam setzt das Mikrofon auf  -  Danach betritt sie die Bühne '}],


/// Experimental Items
[["V_r" , 1],'Question', {q:' Annika betrat die Boutique.               Eine Zeit lang suchte sie nach einer Hose. '}],
[["V_r" , 1],'Question', {q:' Annika verließ die Boutique.               Eine Zeit lang suchte sie nach einer Hose. '}],
[["V_r" , 1],'Question', {q:' Annika zerschnitt die Boutique.               Eine Zeit lang suchte sie nach einer Hose. '}],
[["V_u" , 1],'Question', {q:' Annika verließ die Boutique.               Eine Zeit lang suchte sie nach einem Taxi. '}],
[["V_u" , 1],'Question', {q:' Annika betrat die Boutique.                Eine Zeit lang suchte sie nach einem Taxi. '}],
[["V_u" , 1],'Question', {q:' Annika zerschnitt die Boutique.                Eine Zeit lang suchte sie nach einem Taxi. '}],
[["V_r" , 2],'Question', {q:' Jakob betrat die Bäckerei.                Sofort kaufte  er ein Brötchen. '}],
[["V_r" , 2],'Question', {q:' Jakob verließ die Bäckerei.                Sofort kaufte  er ein Brötchen. '}],
[["V_r" , 2],'Question', {q:' Jakob nähte die Bäckerei.                Sofort kaufte  er ein Brötchen. '}],
[["V_u" , 2],'Question', {q:' Jakob verließ die Bäckerei.                Sofort kaufte er ein Busticket. '}],
[["V_u" , 2],'Question', {q:' Jakob betrat die Bäckerei.                Sofort kaufte er ein Busticket. '}],
[["V_u" , 2],'Question', {q:' Jakob nähte die Bäckerei.                Sofort kaufte er ein Busticket. '}],
[["V_r" , 5],'Question', {q:' Lukas ging in den Gartenmarkt.                Kurz danach ließ er seine Blumen schneiden. '}],
[["V_r" , 5],'Question', {q:' Lukas verließ den Gartenmarkt.                Kurz danach ließ er seine Blumen schneiden. '}],
[["V_r" , 5],'Question', {q:' Lukas blendete den Gartenmarkt.                Kurz danach ließ er seine Blumen schneiden. '}],
[["V_u" , 5],'Question', {q:' Lukas verließ den Gartenmarkt.                Kurz danach ließ er seine Haare schneiden. '}],
[["V_u" , 5],'Question', {q:' Lukas ging in den Gartenmarkt.                Kurz danach ließ er seine Haare schneiden. '}],
[["V_u" , 5],'Question', {q:' Lukas blendete den Gartenmarkt.                Kurz danach ließ er seine Haare schneiden. '}],
[["V_r" , 6],'Question', {q:' Franzi betrat das Fitnessstudio.                Schnell ging sie zum Laufband. '}],
[["V_r" , 6],'Question', {q:' Franzi verließ das Fitnessstudio.                Schnell ging sie zum Laufband. '}],
[["V_r" , 6],'Question', {q:' Franzi klebte das Fitnessstudio.                Schnell ging sie zum Laufband. '}],
[["V_u" , 6],'Question', {q:' Franzi verließ das Fitnessstudio.                Schnell ging sie zur Tiefgarage. '}],
[["V_u" , 6],'Question', {q:' Franzi betrat das Fitnessstudio.                Schnell ging sie zur Tiefgarage. '}],
[["V_u" , 6],'Question', {q:' Franzi klebte das Fitnessstudio.                Schnell ging sie zur Tiefgarage. '}],
[["V_r" , 7],'Question', {q:' Jonas schnitt das Obst weg.                Kurz danach machte sein Vater Salat. '}],
[["V_r" , 7],'Question', {q:' Jonas warf das Obst weg.                Kurz danach machte sein Vater Salat. '}],
[["V_r" , 7],'Question', {q:' Jonas sang das Obst weg.                Kurz danach machte sein Vater Salat. '}],
[["V_u" , 7],'Question', {q:' Jonas warf das Obst weg.                Kurz danach machte sein Vater Ärger. '}],
[["V_u" , 7],'Question', {q:' Jonas schnitt das Obst weg.                Kurz danach machte sein Vater Ärger. '}],
[["V_u" , 7],'Question', {q:' Jonas sang das Obst weg.                Kurz danach machte sein Vater Ärger. '}],
[["V_r" , 8],'Question', {q:' Lea kam zur Metzgerei.                Schnell kaufte sie eine Wurst. '}],
[["V_r" , 8],'Question', {q:' Lea verließ die Metzgerei.                Schnell kaufte sie eine Wurst. '}],
[["V_r" , 8],'Question', {q:' Lea zernagte die Metzgerei.                Schnell kaufte sie eine Wurst. '}],
[["V_u" , 8],'Question', {q:' Lea verließ die Metzgerei.                Schnell╩kaufte sie ein Hemd. '}],
[["V_u" , 8],'Question', {q:' Lea kam zur Metzgerei.                Schnell kaufte sie ein Hemd. '}],
[["V_u" , 8],'Question', {q:' Lea zernagte die Metzgerei.                Schnell kaufte sie ein Hemd. '}],
[["V_r" , 9],'Question', {q:' Claudia fuhr zum See.                Dann öffnete sie den Sonnenschirm. '}],
[["V_r" , 9],'Question', {q:' Claudia verließ den See.                Dann öffnete sie den Sonnenschirm. '}],
[["V_r" , 9],'Question', {q:' Claudia zermahlte den See.                Dann öffnete sie den Sonnenschirm. '}],
[["V_u" , 9],'Question', {q:' Claudia verließ den See.                Dann öffnete sie die Haustör. '}],
[["V_u" , 9],'Question', {q:' Claudia fuhr zum See.                Dann öffnete sie die Haustör. '}],
[["V_u" , 9],'Question', {q:' Claudia zermahlte den See.                Dann öffnete sie die Haustör. '}],
[["V_r" , 10],'Question', {q:' Bruno stieg in die Badewanne.                Sofort nahm er die Seife. '}],
[["V_r" , 10],'Question', {q:' Bruno verließ die Badewanne.                Sofort nahm er die Seife. '}],
[["V_r" , 10],'Question', {q:' Bruno lehrte die Badewanne.                Sofort nahm er die Seife. '}],
[["V_u" , 10],'Question', {q:' Bruno verließ die Badewanne.                Sofort nahm er das T-Shirt. '}],
[["V_u" , 10],'Question', {q:' Bruno stieg in die Badewanne.                Sofort nahm er das T-Shirt. '}],
[["V_u" , 10],'Question', {q:' Bruno lehrte die Badewanne.                Sofort nahm er das T-Shirt. '}],
[["V_r" , 12],'Question', {q:' Manuel ging raus ins Gewitter.                Bald öffnete er seinen Regenschirm. '}],
[["V_r" , 12],'Question', {q:' Manuel flöchtete vorm Gewitter.                Bald öffnete er seinen Regenschirm. '}],
[["V_r" , 12],'Question', {q:' Manuel demötigte das Gewitter.                Bald öffnete er seinen Regenschirm. '}],
[["V_u" , 12],'Question', {q:' Manuel flöchtete vorm Gewitter.                Bald öffnete er seinen Kleiderschrank. '}],
[["V_u" , 12],'Question', {q:' Manuel ging raus ins Gewitter.                Bald öffnete er seinen Kleiderschrank. '}],
[["V_u" , 12],'Question', {q:' Manuel demötigte das Gewitter.                Bald öffnete er seinen Kleiderschrank. '}],
[["V_r" , 13],'Question', {q:' Mia ging raus in die Kälte.                Direkt sah sie den Schneefall. '}],
[["V_r" , 13],'Question', {q:' Mia flöchtete vor  der Kälte.                Direkt sah sie den Schneefall. '}],
[["V_r" , 13],'Question', {q:' Mia belog die Kälte.                Direkt sah sie den Schneefall. '}],
[["V_u" , 13],'Question', {q:' Mia ging raus in die Kälte.                Direkt  sah sie den Sperling. '}],
[["V_u" , 13],'Question', {q:' Mia flöchtete vor der Kälte.                Direkt  sah sie den Sperling. '}],
[["V_u" , 13],'Question', {q:' Mia belog die Kälte.                Direkt  sah sie den Sperling. '}],
[["V_r" , 14],'Question', {q:' Markus betrat die Bank.               Prompt sah er eine lange Schlange zum Geldautomaten. '}],
[["V_r" , 14],'Question', {q:' Markus verließ die Bank.               Prompt sah er eine lange Schlange zum Geldautomaten. '}],
[["V_r" , 14],'Question', {q:' Markus kaute die Bank.               Prompt sah er eine lange Schlange zum Geldautomaten. '}],
[["V_u" , 14],'Question', {q:' Markus verließ die Bank.               Prompt sah er eine lange Schlange zum Straßenbahn. '}],
[["V_u" , 14],'Question', {q:' Markus betrat die Bank.               Prompt sah er eine lange Schlange zum Straßenbahn. '}],
[["V_u" , 14],'Question', {q:' Markus kaute die Bank.               Prompt sah er eine lange Schlange zum Straßenbahn. '}],
[["V_r" , 15],'Question', {q:' Dominik kam spät zur Schule.               Eilig begrößte er seinen Lehrer. '}],
[["V_r" , 15],'Question', {q:' Dominik verließ die Schule.               Eilig begrößte er seinen Lehrer. '}],
[["V_r" , 15],'Question', {q:' Dominik beschuldigte die Schule.               Eilig begrößte er seinen Lehrer. '}],
[["V_u" , 15],'Question', {q:' Dominik verließ die  Schule.               Eilig begrößte er seine Mutter. '}],
[["V_u" , 15],'Question', {q:' Dominik kam spät zur Schule.               Eilig begrößte er seine Mutter. '}],
[["V_u" , 15],'Question', {q:' Dominik beschuldigte die Schule.               Eilig begrößte er seine Mutter. '}],
[["V_r" , 16],'Question', {q:' Emil kam ins Museum.                Gleich sah er das Gemälde. '}],
[["V_r" , 16],'Question', {q:' Emil verließ das Museum.                Gleich sah er das Gemälde. '}],
[["V_r" , 16],'Question', {q:' Emil ertränkte das Museum.                Gleich sah er das Gemälde. '}],
[["V_u" , 16],'Question', {q:' Emil verließ das Museum.                Gleich sah er die Ampel. '}],
[["V_u" , 16],'Question', {q:' Emil kam ins Museum.                Gleich sah er die Ampel. '}],
[["V_u" , 16],'Question', {q:' Emil ertränkte das Museum.                Gleich sah er die Ampel. '}],
[["V_r" , 19],'Question', {q:' Peter betrat die Mensa.                Nach einer Weile setzte er sich an den Esstisch . '}],
[["V_r" , 19],'Question', {q:' Peter verließ die Mensa.                Nach einer Weile setzte er sich an den Esstisch . '}],
[["V_r" , 19],'Question', {q:' Peter trank die Mensa.                Nach einer Weile setzte er sich an den Esstisch . '}],
[["V_u" , 19],'Question', {q:' Peter verließ die Mensa.                Nach einer Weile setzte er sich auf ein Moped. '}],
[["V_u" , 19],'Question', {q:' Peter betrat die Mensa.                Nach einer Weile setzte er sich auf ein Moped. '}],
[["V_u" , 19],'Question', {q:' Peter trank die Mensa.                Nach einer Weile setzte er sich auf ein Moped. '}],
[["V_r" , 20],'Question', {q:' Johan ging zur Vorlesung.                 Er sprach mit seinem Professor. '}],
[["V_r" , 20],'Question', {q:' Johan verpasste die Vorlesung.                 Er sprach mit seinem Professor. '}],
[["V_r" , 20],'Question', {q:' Johan schluckte die Vorlesung.                 Er sprach mit seinem Professor. '}],
[["V_u" , 20],'Question', {q:' Johan verpasste die  Vorlesung.                  Er sprach mit seinem Bruder. '}],
[["V_u" , 20],'Question', {q:' Johanging zur Vorlesung.                  Er sprach mit seinem Bruder. '}],
[["V_u" , 20],'Question', {q:' Johan schluckte die Vorlesung.                  Er sprach mit seinem Bruder. '}],
[["V_r" , 21],'Question', {q:' Adele kam zu einer bernachtungsparty.               Sie holte ihr Nachthemd. '}],
[["V_r" , 21],'Question', {q:' Adele verließ eine Übernachtungsparty.               Sie holte ihr Nachthemd. '}],
[["V_r" , 21],'Question', {q:' Adele nähte eine Übernachtungsparty.               Sie holte ihr Nachthemd. '}],
[["V_u" , 21],'Question', {q:' Adele verließ eine Übernachtungsparty.               Sie holte ihren  Regenmantel. '}],
[["V_u" , 21],'Question', {q:' Adele kam zu einer Übernachtungsparty.               Sie holte ihren  Regenmantel. '}],
[["V_u" , 21],'Question', {q:' Adele nähte eine Übernachtungsparty.               Sie holte ihren  Regenmantel. '}],
[["V_r" , 22],'Question', {q:' Louis fuhr zum Autohaus.                Er sprach mit einem Berater. '}],
[["V_r" , 22],'Question', {q:' Louis verließ das Autohaus.                Er sprach mit einem Berater. '}],
[["V_r" , 22],'Question', {q:' Louis nähte das Autohaus.                Er sprach mit einem Berater. '}],
[["V_u" , 22],'Question', {q:' Louis verließ das Autohaus.                Er sprach mit einem Kellner. '}],
[["V_u" , 22],'Question', {q:' Louis fuhr zum Autohaus.                Er sprach mit einem Kellner. '}],
[["V_u" , 22],'Question', {q:' Louis nähte das Autohaus.                Er sprach mit einem Kellner. '}],
[["V_r" , 24],'Question', {q:' Hans und seine Freunde gingen zum Picknick.                Zuerst nahmen sie den Korb. '}],
[["V_r" , 24],'Question', {q:' Hans und seine Freunde kamen von dem Picknick.                Zuerst nahmen sie den Korb. '}],
[["V_r" , 24],'Question', {q:' Hans und seine Freunde telefonierten mit dem Picknick.                Zuerst nahmen sie den Korb. '}],
[["V_u" , 24],'Question', {q:' Hans und seine Freunde  gingen zum Picknick.                Zuerst nahmen sie die Post. '}],
[["V_u" , 24],'Question', {q:' Hans und seine Freunde  kamen von dem Picknick.                Zuerst nahmen sie die Post. '}],
[["V_u" , 24],'Question', {q:' Hans und seine Freunde telefonierten mit dem Picknick.                Zuerst nahmen sie die Post. '}],
[["V_r" , 25],'Question', {q:' Katarina badete ihren Sohn.                Sie nahm die Seife. '}],
[["V_r" , 25],'Question', {q:' Katarina trocknete ihren Sohn.                Sie nahm die Seife. '}],
[["V_r" , 25],'Question', {q:' Katarina baute ihren Sohn.                Sie nahm die Seife. '}],
[["V_u" , 25],'Question', {q:' Katarina trocknete ihren Sohn.                Sie nahm die Socken. '}],
[["V_u" , 25],'Question', {q:' Katarina badete ihren Sohn.                Sie nahm die Socken. '}],
[["V_u" , 25],'Question', {q:' Katarina baute ihren Sohn.                Sie nahm die Socken. '}],
[["V_r" , 26],'Question', {q:' Mary betrat das Postamt.                Sofort bekam sie ein Paket. '}],
[["V_r" , 26],'Question', {q:' Mary verließ das Postamt.                Sofort bekam sie ein Paket. '}],
[["V_r" , 26],'Question', {q:' Mary massierte das Postamt.                Sofort bekam sie ein Paket. '}],
[["V_u" , 26],'Question', {q:' Mary verließ das Postamt.                Sofort bekam sie ein Taxi. '}],
[["V_u" , 26],'Question', {q:' Mary betrat das Postamt.                Sofort bekam sie ein Taxi. '}],
[["V_u" , 26],'Question', {q:' Mary massierte das Postamt.                Sofort bekam sie ein Taxi. '}],
[["V_r" , 27],'Question', {q:' Annika ging zu einem Geschäftstreffen.                Sie trug ihren Hosenanzug. '}],
[["V_r" , 27],'Question', {q:' Annika kam von einem Geschäftstreffen.                Sie trug ihren Hosenanzug. '}],
[["V_r" , 27],'Question', {q:' Annika packte ein Geschäftstreffen.                Sie trug ihren Hosenanzug. '}],
[["V_u" , 27],'Question', {q:' Annika  ging zu einem Geschäftstreffen.                Sie trug ihre Hausschuhe. '}],
[["V_u" , 27],'Question', {q:' Annika kam von einem Geschäftstreffen.                Sie trug ihre Hausschuhe. '}],
[["V_u" , 27],'Question', {q:' Annika packte ein Geschäftstreffen.                Sie trug ihre Hausschuhe. '}],
[["V_r" , 28],'Question', {q:' Peter kam zum Bahnhof.                Wenig später kaufte er eine Fahrkarte. '}],
[["V_r" , 28],'Question', {q:' Peter verließ den Bahnhof.                Wenig später kaufte er eine Fahrkarte. '}],
[["V_r" , 28],'Question', {q:' Peter badete den Bahnhof.                Wenig später kaufte er eine Fahrkarte. '}],
[["V_u" , 28],'Question', {q:' Peter verließ den Bahnhof.                Wenig später kaufte er eine Theaterkarte. '}],
[["V_u" , 28],'Question', {q:' Peter kam zum Bahnhof.                Wenig später kaufte er eine Theaterkarte. '}],
[["V_u" , 28],'Question', {q:' Peter badete den Bahnhof.                Wenig später kaufte er eine Theaterkarte. '}],
[["V_r" , 29],'Question', {q:' Mathias backte die Geburtstagstorte.                Er mischte den Kuchenteig. '}],
[["V_r" , 29],'Question', {q:' Mathias aß die Geburtstagstorte.                Er mischte den Kuchenteig. '}],
[["V_r" , 29],'Question', {q:' Mathias bleichte die Geburtstagstorte.                Er mischte den Kuchenteig. '}],
[["V_u" , 29],'Question', {q:' Mathias aß die Geburtstagstorte.                Er mischte die Spielkarten. '}],
[["V_u" , 29],'Question', {q:' Mathias backte die Geburtstagstorte.                Er mischte die Spielkarten. '}],
[["V_u" , 29],'Question', {q:' Mathias bleichte die Geburtstagstorte.                Er mischte die Spielkarten. '}],
[["V_r" , 30],'Question', {q:' Erika ging zu einem Fußballspiel.                Sie eilte zum Stadion. '}],
[["V_r" , 30],'Question', {q:' Erika kam von einem Fußballspiel.                Sie eilte zum Stadion. '}],
[["V_r" , 30],'Question', {q:' Erika malte mit einem Fußballspiel.                Sie eilte zum Stadion. '}],
[["V_u" , 30],'Question', {q:' Erika kam von einem Fußballspiel.                Sie eilte zum Restaurant. '}],
[["V_u" , 30],'Question', {q:' Erika ging zu einem Fußballspiel.                Sie eilte zum Restaurant. '}],
[["V_u" , 30],'Question', {q:' Erika malte mit einem Fußballspiel.                Sie eilte zum Restaurant. '}],
[["V_r" , 31],'Question', {q:' Michael verließ die Apotheke.                 Er kaufte Vitamine. '}],
[["V_r" , 31],'Question', {q:' Michael ging in die Apotheke.                 Er kaufte Vitamine. '}],
[["V_r" , 31],'Question', {q:' Michael nähte die Apotheke.                 Er kaufte Vitamine. '}],
[["V_u" , 31],'Question', {q:' Michael verließ die Apotheke.                 Er kaufte Rotwein. '}],
[["V_u" , 31],'Question', {q:' Michael ging in die Apotheke.                 Er kaufte Rotwein. '}],
[["V_u" , 31],'Question', {q:' Michael nähte die Apotheke.                 Er kaufte Rotwein. '}],
[["V_r" , 32],'Question', {q:' Susan bekam eine Grippe.                Sie hielt Bettruhe. '}],
[["V_r" , 32],'Question', {q:' Susan genas von einer Grippe.                Sie hielt Bettruhe. '}],
[["V_r" , 32],'Question', {q:' Susan badete eine Grippe.                Sie hielt Bettruhe. '}],
[["V_u" , 32],'Question', {q:' Susan genas von einer Grippe.                Sie hielt eine Feier. '}],
[["V_u" , 32],'Question', {q:' Susan bekam eine Grippe.                Sie hielt eine Feier. '}],
[["V_u" , 32],'Question', {q:' Susan badete eine Grippe.                Sie hielt eine Feier. '}],
[["V_r" , 33],'Question', {q:' Renate ging zum Schneider.                Sie suchte nach einem Kleid. '}],
[["V_r" , 33],'Question', {q:' Renate kam vom Schneider.                Sie suchte nach einem Kleid. '}],
[["V_r" , 33],'Question', {q:' Renate braute den Schneider.                Sie suchte nach einem Kleid. '}],
[["V_u" , 33],'Question', {q:' Renate kam vom Schneider.                Sie suchte nach ihrem Schlössel. '}],
[["V_u" , 33],'Question', {q:' Renate ging zum Schneider.                Sie suchte nach ihrem Schlössel. '}],
[["V_u" , 33],'Question', {q:' Renate braute den Schneider.                Sie suchte nach ihrem Schlössel. '}],
[["V_r" , 34],'Question', {q:' Thomas ging zum Schlosser.                Er kopierte seinen Schlössel . '}],
[["V_r" , 34],'Question', {q:' Thomas kam vom Schlosser.                Er kopierte seinen Schlössel. '}],
[["V_r" , 34],'Question', {q:' Thomas aß den Schlosser.                Er kopierte seinen Schlössel . '}],
[["V_u" , 34],'Question', {q:' Thomas kam vom Schlosser.                Er kopierte seine Unterlagen. '}],
[["V_u" , 34],'Question', {q:' Thomas ging zum Schlosser.                Er kopierte seine Unterlagen. '}],
[["V_u" , 34],'Question', {q:' Thomas aß den Schlosser.                Er kopierte seine Unterlagen. '}],
[["V_r" , 35],'Question', {q:' Klaus fötterte die Katze.                Er beföllte einen Napf. '}],
[["V_r" , 35],'Question', {q:' Klaus tränkte die Katze.                Er beföllte einen Napf. '}],
[["V_r" , 35],'Question', {q:' Klaus angelte die Katze.                Er beföllte einen Napf. '}],
[["V_u" , 35],'Question', {q:' Klaus tränkte die Katze.                Er beföllte eine Kanne. '}],
[["V_u" , 35],'Question', {q:' Klaus fötterte die Katze.                Er beföllte eine Kanne. '}],
[["V_u" , 35],'Question', {q:' Klaus angelte die Katze.                Er beföllte eine Kanne. '}],
[["V_r" , 36],'Question', {q:' Lea und ihre Freunde gingen zum Sportgeschäft.                Sie bezahlten den Fußball. '}],
[["V_r" , 36],'Question', {q:' Lea und ihre Freunde kamen aus dem Sportgeschäft.                Sie bezahlten den Fußball. '}],
[["V_r" , 36],'Question', {q:' Lea und ihre Freunde zwickten das Sportgeschäft.                Sie bezahlten den Fußball. '}],
[["V_u" , 36],'Question', {q:' Lea und ihre Freunde kamen aus dem Sportgeschäft.                Sie bezahlten den Kaffee. '}],
[["V_u" , 36],'Question', {q:' Lea und ihre Freunde gingen zum Sportgeschäft.                Sie bezahlten den Kaffee. '}],
[["V_u" , 36],'Question', {q:' Lea und ihre Freunde zwickten das Sportgeschäft.                Sie bezahlten den Kaffee. '}],
[["V_r" , 38],'Question', {q:' Susi betrat das Tiergehege.                Präzise untersuchte sie die Hunde. '}],
[["V_r" , 38],'Question', {q:' Susi kopierte das Tiergehege.                Präzise untersuchte sie die Hunde. '}],
[["V_r" , 38],'Question', {q:' Susi betrat das Tiergehege.                Präzise untersuchte sie die Hunde. '}],
[["V_u" , 38],'Question', {q:' Susi verließ das Tiergehege.                Präzise untersuchte sie die Häuser. '}],
[["V_u" , 38],'Question', {q:' Susi betrat das Tiergehege.                Präzise untersuchte sie die Häuser. '}],
[["V_u" , 38],'Question', {q:' Susi kopierte das Tiergehege.                Präzise untersuchte sie die Häuser. '}],
[["V_r" , 39],'Question', {q:' Claudia betrat das Tiergeschäft.                Eine Zeit lang stand sie vor dem Futter. '}],
[["V_r" , 39],'Question', {q:' Claudia verließ das Tiergeschäft.                Eine Zeit lang stand sie vor dem Futter. '}],
[["V_r" , 39],'Question', {q:' Claudia briet das Tiergeschäft.                Eine Zeit lang stand sie vor dem Futter. '}],
[["V_u" , 39],'Question', {q:' Claudia verließ das Tiergeschäft.                Eine Zeit lang stand sie vor der Optiker. '}],
[["V_u" , 39],'Question', {q:' Claudia betrat das Tiergeschäft.                Eine Zeit lang stand sie vor der Optiker. '}],
[["V_u" , 39],'Question', {q:' Claudia briet das Tiergeschäft.                Eine Zeit lang stand sie vor der Optiker. '}],
[["V_r" , 40],'Question', {q:' Hugo betrat die Buchhandlung.                Schnell suchte er einen Krimi. '}],
[["V_r" , 40],'Question', {q:' Hugo verließ die Buchhandlung.                Schnell suchte er einen Krimi. '}],
[["V_r" , 40],'Question', {q:' Hugo mahlte die Buchhandlung.                Schnell suchte er einen Krimi. '}],
[["V_u" , 40],'Question', {q:' Hugo verließ die Buchhandlung.                Schnell suchte er eine Orange. '}],
[["V_u" , 40],'Question', {q:' Hugo betrat die Buchhandlung.                Schnell suchte er eine Orange. '}],
[["V_u" , 40],'Question', {q:' Hugo mahlte die Buchhandlung.                Schnell suchte er eine Orange. '}],
[["V_r" , 41],'Question', {q:' Sven betrat die Apotheke.                Schnell kaufte er die Salbe. '}],
[["V_r" , 41],'Question', {q:' Sven verließ die Apotheke.                Schnell kaufte er die Salbe. '}],
[["V_r" , 41],'Question', {q:' Sven salzte die Apotheke.                Schnell kaufte er die Salbe. '}],
[["V_u" , 41],'Question', {q:' Sven verließ die Apotheke.                Schnell kaufte er den Döner. '}],
[["V_u" , 41],'Question', {q:' Sven betrat die Apotheke.                Schnell kaufte er den Döner. '}],
[["V_u" , 41],'Question', {q:' Sven salzte die Apotheke.                Schnell kaufte er den Döner. '}],
[["V_r" , 42],'Question', {q:' Jörgen betrat die Bäckerei.                Wenig später sah er das Croissant. '}],
[["V_r" , 42],'Question', {q:' Jörgen verließ die Bäckerei.                Wenig später sah er das Croissant. '}],
[["V_r" , 42],'Question', {q:' Jörgen tanzte die Bäckerei.                Wenig später sah er das Croissant. '}],
[["V_u" , 42],'Question', {q:' Jörgen verließ die Bäckerei.                Wenig später sah er den Verkehr. '}],
[["V_u" , 42],'Question', {q:' Jörgen betrat die Bäckerei.                Wenig später sah er den Verkehr. '}],
[["V_u" , 42],'Question', {q:' Jörgen tanzte die Bäckerei.                Wenig später sah er den Verkehr. '}],
[["V_r" , 43],'Question', {q:' Frauke ging ins Stadion.                Schnell fand sie ihre Triböne. '}],
[["V_r" , 43],'Question', {q:' Frauke verließ das Stadion.                Schnell fand sie ihre Triböne. '}],
[["V_r" , 43],'Question', {q:' Frauke druckte das Stadion.                Schnell fand sie ihre Triböne. '}],
[["V_u" , 43],'Question', {q:' Frauke verließ das Stadion.                Schnell fand sie ihren Roller. '}],
[["V_u" , 43],'Question', {q:' Frauke ging ins Stadion.                Schnell fand sie ihren Roller. '}],
[["V_u" , 43],'Question', {q:' Frauke druckte das Stadion.                Schnell fand sie ihren Roller. '}],
[["V_r" , 44],'Question', {q:' Bernd betrat den Kiosk.                Dann kaufte er eine Zeitung. '}],
[["V_r" , 44],'Question', {q:' Bernd verließ den Kiosk.                Dann kaufte er eine Zeitung. '}],
[["V_r" , 44],'Question', {q:' Bernd strickte den Kiosk.                Dann kaufte er eine Zeitung. '}],
[["V_u" , 44],'Question', {q:' Bernd verließ den Kiosk.                Dann kaufte er eine Pfanne. '}],
[["V_u" , 44],'Question', {q:' Bernd betrat den Kiosk.                Dann kaufte er eine Pfanne. '}],
[["V_u" , 44],'Question', {q:' Bernd strickte den Kiosk.                Dann kaufte er eine Pfanne. '}],
[["V_r" , 46],'Question', {q:' Kim betrat das Hotel.                Gleich ging sie zum Concierge. '}],
[["V_r" , 46],'Question', {q:' Kim verließ das Hotel.                Gleich ging sie zum Concierge. '}],
[["V_r" , 46],'Question', {q:' Kim jagte das Hotel.                Gleich ging sie zum Concierge. '}],
[["V_u" , 46],'Question', {q:' Kim verließ das Hotel.                Gleich ging sie zum Ohrenarzt. '}],
[["V_u" , 46],'Question', {q:' Kim betrat das Hotel.                Gleich ging sie zum Ohrenarzt. '}],
[["V_u" , 46],'Question', {q:' Kim jagte das Hotel.                Gleich ging sie zum Ohrenarzt. '}],
[["V_r" , 47],'Question', {q:' Susi betrat die Arztpraxis.                Freundlich sprach sie mit der Krankenschwester. '}],
[["V_r" , 47],'Question', {q:' Susi verließ die Arztpraxis.                Freundlich sprach sie mit der Krankenschwester. '}],
[["V_r" , 47],'Question', {q:' Susi badete die Arztpraxis.                Freundlich sprach sie mit der Krankenschwester. '}],
[["V_u" , 47],'Question', {q:' Susi verließ die Arztpraxis.                Freundlich sprach sie mit dem Abteilungsleiter. '}],
[["V_u" , 47],'Question', {q:' Susi betrat die Arztpraxis.                Freundlich sprach sie mit dem Abteilungsleiter. '}],
[["V_u" , 47],'Question', {q:' Susi badete die Arztpraxis.                Freundlich sprach sie mit dem Abteilungsleiter. '}],
[["V_r" , 48],'Question', {q:' Manfred erreichte das Theater.               Wenig später ging er zur Loge. '}],
[["V_r" , 48],'Question', {q:' Manfred verließ das Theater.               Wenig später ging er zur Loge. '}],
[["V_r" , 48],'Question', {q:' Manfred fötterte das Theater.               Wenig später ging er zur Loge. '}],
[["V_u" , 48],'Question', {q:' Manfred verließ das Theater.               Wenig später ging er zum Moped. '}],
[["V_u" , 48],'Question', {q:' Manfred erreichte das Theater.               Wenig später ging er zum Moped. '}],
[["V_u" , 48],'Question', {q:' Manfred fötterte das Theater.               Wenig später ging er zum Moped. '}],
[["V_r" , 49],'Question', {q:' Werner betrat die Kirche.                Nachdenklich betrachtete er die Kerzen. '}],
[["V_r" , 49],'Question', {q:' Werner verließ die Kirche.                Nachdenklich betrachtete er die Kerzen. '}],
[["V_r" , 49],'Question', {q:' Werner dönstete die Kirche.                Nachdenklich betrachtete er die Kerzen. '}],
[["V_u" , 49],'Question', {q:' Werner verließ die Kirche.                Nachdenklich betrachtete er die Wolke. '}],
[["V_u" , 49],'Question', {q:' Werner betrat die Kirche.                Nachdenklich betrachtete er die Wolke. '}],
[["V_u" , 49],'Question', {q:' Werner verließ die Kirche.                Nachdenklich betrachtete er die Wolke. '}],
[["V_r" , 50],'Question', {q:' Gerda betrat das Spa.                Nach einer Weile bekam sie eine Kopfmassage. '}],
[["V_r" , 50],'Question', {q:' Gerda verließ das Spa.                Nach einer Weile bekam sie eine Kopfmassage. '}],
[["V_r" , 50],'Question', {q:' Gerda pörierte das Spa.                Nach einer Weile bekam sie eine Kopfmassage. '}],
[["V_u" , 50],'Question', {q:' Gerda verließ das Spa.                Nach einer Weile bekam sie einen Blumenstrauß. '}],
[["V_u" , 50],'Question', {q:' Gerda betrat das Spa.                Nach einer Weile bekam sie einen Blumenstrauß. '}],
[["V_u" , 50],'Question', {q:' Gerda pörierte das Spa.                Nach einer Weile bekam sie einen Blumenstrauß. '}],
[["V_r" , 51],'Question', {q:' Augusta betrat die Reitschule.                Schnell setzte sie sich auf den Pferdesattel. '}],
[["V_r" , 51],'Question', {q:' Augusta verließ die Reitschule.                Schnell setzte sie sich auf den Pferdesattel. '}],
[["V_r" , 51],'Question', {q:' Augusta pfefferte die Reitschule.                Schnell setzte sie sich auf den Pferdesattel. '}],
[["V_u" , 51],'Question', {q:' Augusta verließ die Reitschule.                Schnell setzte sie sich auf den Fahrradsattel. '}],
[["V_u" , 51],'Question', {q:' Augusta betrat die Reitschule.                Schnell setzte sie sich auf den Fahrradsattel. '}],
[["V_u" , 51],'Question', {q:' Augusta pfefferte die Reitschule.                Schnell setzte sie sich auf den Fahrradsattel. '}],
[["V_r" , 52],'Question', {q:' Gerhardt begann seinen Feuerwehreinsatz.                Er nahm den Gummischlauch. '}],
[["V_r" , 52],'Question', {q:' Gerhardt verpasste seinen Feuerwehreinsatz.                Er nahm den Gummischlauch. '}],
[["V_r" , 52],'Question', {q:' Gerhardt kaute seinen Feuerwehreinsatz.                Er nahm den Gummischlauch. '}],
[["V_u" , 52],'Question', {q:' Gerhardt verpasste seinen Feuerwehreinsatz.                Er nahm den Bröckentag. '}],
[["V_u" , 52],'Question', {q:' Gerhardt begann seinen Feuerwehreinsatz.                Er nahm den Bröckentag. '}],
[["V_u" , 52],'Question', {q:' Gerhardt kaute seinen Feuerwehreinsatz.                Er nahm den Bröckentag. '}],
[["V_r" , 53],'Question', {q:' Eleonore begann das Fußballspiel.                Sofort machte sie ein Eigentor. '}],
[["V_r" , 53],'Question', {q:' Eleonore beendete das Fußballspiel.                Sofort machte sie ein Eigentor. '}],
[["V_r" , 53],'Question', {q:' Eleonore zöchtete das Fußballspiel.                Sofort machte sie ein Eigentor. '}],
[["V_u" , 53],'Question', {q:' Eleonore beendete das Fußballspiel.                Sofort machte sie ihre Einkäufe. '}],
[["V_u" , 53],'Question', {q:' Eleonore begann das Fußballspiel.                Sofort machte sie ihre Einkäufe. '}],
[["V_u" , 53],'Question', {q:' Eleonore zöchtete das Fußballspiel.                Sofort machte sie ihre Einkäufe. '}],
[["V_r" , 55],'Question', {q:' Jenni schnitt die Gurken.                Dann machte sie einen Salat. '}],
[["V_r" , 55],'Question', {q:' Jenni zerkochte die Gurken.                Dann machte sie einen Salat. '}],
[["V_r" , 55],'Question', {q:' Jenni bebaute die Gurken.                Dann machte sie einen Salat. '}],
[["V_u" , 55],'Question', {q:' Jenni zerkochte die Gurken.                Dann machte sie einen Kuchen. '}],
[["V_u" , 55],'Question', {q:' Jenni schnitt die Gurken.                Dann machte sie einen Kuchen. '}],
[["V_u" , 55],'Question', {q:' Jenni bebaute die Gurken.                Dann machte sie einen Kuchen. '}],
[["V_r" , 56],'Question', {q:' Michael töpferte eine Vase.                Dann stellte  er das Gefäß. '}],
[["V_r" , 56],'Question', {q:' Michael zerstörte eine Vase.                Dann stellte  er das Gefäß. '}],
[["V_r" , 56],'Question', {q:' Michael fischte eine Vase.                Dann stellte  er das Gefäß. '}],
[["V_u" , 56],'Question', {q:' Michael zerstörte eine Vase.                Dann stellte er den Überrest. '}],
[["V_u" , 56],'Question', {q:' Michael töpferte eine Vase.                Dann stellte er den Überrest. '}],
[["V_u" , 56],'Question', {q:' Michael fischte eine Vase.                Dann stellte er den Überrest. '}],
[["V_r" , 59],'Question', {q:' Maximilian beendete ihr Jurastudium an der Universität.                Gleich danach arbeitete er als Anwalt. '}],
[["V_r" , 59],'Question', {q:' Maximilian begann ihr Jurastudium an der Universität.                Gleich danach arbeitete er als Anwalt. '}],
[["V_r" , 59],'Question', {q:' Maximilian zerriss ihr Jurastudium an der Universität.                Gleich danach arbeitete er als Anwalt. '}],
[["V_u" , 59],'Question', {q:' Maximilian begann ihr Jurastudium an der Universität.                Gleich danach arbeitete er als Kellner. '}],
[["V_u" , 59],'Question', {q:' Maximilian beendete ihr Jurastudium an der Universität.                Gleich danach arbeitete er als Kellner. '}],
[["V_u" , 59],'Question', {q:' Maximilian zerriss ihr Jurastudium an der Universität.                Gleich danach arbeitete er als Kellner. '}],
[["V_r" , 60],'Question', {q:' Jonathan ging zum Bergsteigen.                Dann stellte er sich auf den Gipfel. '}],
[["V_r" , 60],'Question', {q:' Jonathan kam vom Bergsteigen.                Dann stellte er sich auf den Gipfel. '}],
[["V_r" , 60],'Question', {q:' Jonathan brach das Bergsteigen.                Dann stellte er sich auf den Gipfel. '}],
[["V_u" , 60],'Question', {q:' Jonathan kam vom Bergsteigen.                Dann stellte er sich auf den Parkplatz. '}],
[["V_u" , 60],'Question', {q:' Jonathan ging zum Bergsteigen.                Dann stellte er sich auf den Parkplatz. '}],
[["V_u" , 60],'Question', {q:' Jonathan brach das Bergsteigen.                Dann stellte er sich auf den Parkplatz. '}],
[["V_r" , 61],'Question', {q:' Cedric kaufte die Tabletten.                Später öbergab er die Medizin seiner Mutter. '}],
[["V_r" , 61],'Question', {q:' Cedric verlor die Tabletten.                Später öbergab er die Medizin seiner Mutter. '}],
[["V_r" , 61],'Question', {q:' Cedric belog die Tabletten.                Später öbergab er die Medizin seiner Mutter. '}],
[["V_u" , 61],'Question', {q:' Cedric verlor die Tabletten.                Später öbergab er die Rechnung seiner Mutter. '}],
[["V_u" , 61],'Question', {q:' Cedric kaufte die Tabletten.                Später öbergab er die Rechnung seiner Mutter. '}],
[["V_u" , 61],'Question', {q:' Cedric belog die Tabletten.                Später öbergab er die Rechnung seiner Mutter. '}],
[["V_r" , 65],'Question', {q:' Lasse begann einen Tanzkurs.                Sofort ging er in die Tanzschule . '}],
[["V_r" , 65],'Question', {q:' Lasse beendete einen Tanzkurs.                Sofort ging er in die Tanzschule . '}],
[["V_r" , 65],'Question', {q:' Lasse schwamm einen Tanzkurs.                Sofort ging er in die Tanzschule . '}],
[["V_u" , 65],'Question', {q:' Lasse beendete einen Tanzkurs.                 Sofort ging er in ein Restaurant. '}],
[["V_u" , 65],'Question', {q:' Lasse begann einen Tanzkurs.                 Sofort ging er in ein Restaurant. '}],
[["V_u" , 65],'Question', {q:' Lasse schwamm einen Tanzkurs.                 Sofort ging er in ein Restaurant. '}],
[["V_r" , 67],'Question', {q:' Gregori erhob Daten.                Dann begann er mit der Analyse. '}],
[["V_r" , 67],'Question', {q:' Gregori löschte Daten.                Dann begann er mit der Analyse. '}],
[["V_r" , 67],'Question', {q:' Gregori briet Daten.                Dann begann er mit der Analyse. '}],
[["V_u" , 67],'Question', {q:' Gregori löschte Daten.                Dann begann er mit der Panik. '}],
[["V_u" , 67],'Question', {q:' Gregori erhob Daten.                Dann begann er mit der Panik. '}],
[["V_u" , 67],'Question', {q:' Gregori briet Daten.                Dann begann er mit der Panik. '}],
[["V_r" , 68],'Question', {q:' Martin spielte die Geige.                Dann verstaute er behutsam den Bogen. '}],
[["V_r" , 68],'Question', {q:' Martin zerstörte die Geige.                Dann verstaute er behutsam den Bogen. '}],
[["V_r" , 68],'Question', {q:' Martin angelte die Geige.                Dann verstaute er behutsam den Bogen. '}],
[["V_u" , 68],'Question', {q:' Martin spielte die Trompete.                Dann verstaute er behutsam den Hammer. '}],
[["V_u" , 68],'Question', {q:' Martin zerstörte die Trompete.                Dann verstaute er behutsam den Hammer. '}],
[["V_u" , 68],'Question', {q:' Martin angelte die Trompete.                Dann verstaute er behutsam den Hammer. '}],
[["V_r" , 69],'Question', {q:' Mark eröffnete eine neue Bankfiliale.                Dann begrößte er die Kunden. '}],
[["V_r" , 69],'Question', {q:' Mark schloss eine neue Bankfiliale.                Dann begrößte er die Kunden. '}],
[["V_r" , 69],'Question', {q:' Mark salbte eine neue Bankfiliale.                Dann begrößte er die Kunden. '}],
[["V_u" , 69],'Question', {q:' Mark schloss eine neue Bankfiliale.                Dann begrößte er den Buttler. '}],
[["V_u" , 69],'Question', {q:' Mark eröffnete eine neue Bankfiliale.                Dann begrößte er den Buttler. '}],
[["V_u" , 69],'Question', {q:' Mark salbte eine neue Bankfiliale.                Dann begrößte er den Buttler. '}],
[["V_r" , 71],'Question', {q:' Theodor beendete seine Schicht.                Dann machte er Feierabend. '}],
[["V_r" , 71],'Question', {q:' Theodor begann seine Schicht.                Dann machte er Feierabend. '}],
[["V_r" , 71],'Question', {q:' Theodor zerlumpte seine Schicht.                Dann machte er Feierabend. '}],
[["V_u" , 71],'Question', {q:' Theodor beendete seine Schicht.                Dann machte er einen Fehler. '}],
[["V_u" , 71],'Question', {q:' Theodor begann seine Schicht.                Dann machte er einen Fehler. '}],
[["V_u" , 71],'Question', {q:' Theodor zerlumpte seine Schicht.                Dann machte er einen Fehler. '}],
[["V_r" , 72],'Question', {q:' Markus betrat die Werkstatt.                Höflich sprach er mit einem Mechaniker. '}],
[["V_r" , 72],'Question', {q:' Markus verließ die Werkstatt.                Höflich sprach er mit einem Mechaniker. '}],
[["V_r" , 72],'Question', {q:' Markus badete die Werkstatt.                Höflich sprach er mit einem Mechaniker. '}],
[["V_u" , 72],'Question', {q:' Markus verließ die Werkstatt.                Höflich sprach er mit einem Rechtsanwalt. '}],
[["V_u" , 72],'Question', {q:' Markus betrat die Werkstatt.                Höflich sprach er mit einem Rechtsanwalt. '}],
[["V_u" , 72],'Question', {q:' Markus badete die Werkstatt.                Höflich sprach er mit einem Rechtsanwalt. '}]

];