/// CAPEXP Association Task
/// 3 November 2019


var shuffleSequence = seq(
                          "setcounter", // set counter immediately to start next Latin square list
                          "Welcome",
                          "Consent",
                          "Instructions01",
                          sepWith("sep",
                              seq("practice")),
                          "Instructions02",
                          sepWith("sep",
                               rshuffle(anyOf(
                                   "A_mcverbAB", "B_mcverbCD", "C_rcverbAC", "D_rcverbBD", "E_rcnounAC", "F_rcnounBD"))),
                          "sr",
                          "Outro",
                          "Close"
                          );

var showProgressBar =        true;
var progressBarText =        "Fortschritt";
var continueMessage =        "Hier klicken um fortzufahren.";
var manualSendResults =      true;
var sendingResultsMessage =  "Die Ergebnisse werden an den Server gesendet.";
var completionMessage =      "Die Ergebnisse wurden erfolgreich an den Server gesendet. Sie erhalten nun den Prolific-Completion Code";


var defaults = [
    "Form",{continueMessage:"Hier klicken um fortzufahren."},
    "Message",{continueMessage:"Hier klicken um fortzufahren."},
    "Question",{
        as: [
                [1,"1"],
                [2,"2"],
                [3,"3"],
                [4,"4"],
                [5,"5"],
                [6,"6"],
                [7,"7"]
            ],
        presentAsScale: true,
        leftComment: "nicht plausibel",
        rightComment: "stark plausibel"}
];


var items =[
    ["setcounter", "__SetCounter__", {  }],

    [ "Welcome",
      "Form",
      {"html": {include: "Welcome.html" }}
    ],

    [ "Consent",
      "Form",
      {"html": {include: "Consent.html" }}
    ],

    [ "Instructions01",
      "Form",
      {"html": {include: "Instructions01.html" }}
    ],

    [ "Instructions02",
      "Form",
      {"html": {include: "Instructions02.html" }}
    ],

    [ "Outro",
      "Form",
      {"html": {include: "Outro.html" }}
    ],

    [ "Close",
      "Message",
      { html: "Sie können das Fenster jetzt schließen.", transfer: null}
    ],

    [ "sep",
      "Separator",
      {transfer: 500, normalMessage:""}
    ],

	["sr", "__SendResults__", { }],


  ["practice", 'Question',{q:'Bushaltestelle   -   Stereoanlage '}],
  ["practice", 'Question',{q:'Büro   -   Aktenvernichter '}],
  ["practice", 'Question',{q:'Gebäude   -   Sandburg '}],
  ["practice", 'Question',{q:'Teilung   -   Harke '}],
  ["practice", 'Question',{q:'Spiegel   -   Sofa '}],
  ["practice", 'Question',{q:'Misthaufen   -   Vogelkäfig '}],
  ["practice", 'Question',{q:'Lenkung   -   Kekse '}],


/// Experimental Items

  [["C_r" , 1],'Question', {q:' Schminke - Lippenstift '}],
[["C_u" , 1],'Question', {q:' Schminke - Geld '}],
[["C_r" , 2],'Question', {q:' Sandburg - Wassergraben '}],
[["C_u" , 2],'Question', {q:' Sandburg - Knetfigur '}],
[["C_r" , 3],'Question', {q:' Luftpolsterfolie - Postpaket '}],
[["C_u" , 3],'Question', {q:' Luftpolsterfolie - Papiertüte '}],
[["C_r" , 4],'Question', {q:' Fitnessstudio - Ausdauer '}],
[["C_u" , 4],'Question', {q:' Fitnessstudio - Buch '}],
[["C_r" , 5],'Question', {q:' Romantik - Duftkerze '}],
[["C_u" , 5],'Question', {q:' Romantik - Horrormaske '}],
[["C_r" , 6],'Question', {q:' Musik - Schallplatte '}],
[["C_u" , 6],'Question', {q:' Musik - Schaumbad '}],
[["C_r" , 7],'Question', {q:' Streit - Argumentieren '}],
[["C_u" , 7],'Question', {q:' Streit - Babysitten '}],
[["C_r" , 8],'Question', {q:' Fahrrad - Gangschaltung '}],
[["C_u" , 8],'Question', {q:' Fahrrad - Gesellschaftsspiel '}],
[["C_r" , 9],'Question', {q:' Hund - Gassi '}],
[["C_u" , 9],'Question', {q:' Hund - Bummeln '}],
[["C_r" , 10],'Question', {q:' Schrank - Brett '}],
[["C_u" , 10],'Question', {q:' Schrank - Müllsack '}],
[["C_r" , 11],'Question', {q:' Blume - Gießkanne '}],
[["C_u" , 11],'Question', {q:' Blume - Handtuch '}],
[["C_r" , 12],'Question', {q:' Vogelkäfig - Napf '}],
[["C_u" , 12],'Question', {q:' Vogelkäfig - Fenster '}],
[["C_r" , 13],'Question', {q:' Blume - Vase '}],
[["C_u" , 13],'Question', {q:' Blume - Besen '}],
[["C_r" , 14],'Question', {q:' Pizza - Teig '}],
[["C_u" , 14],'Question', {q:' Pizza - Topf '}],
[["C_r" , 15],'Question', {q:' Mathe-Hausaufgabe - Taschenrechner '}],
[["C_u" , 15],'Question', {q:' Mathe-Hausaufgabe - Jacke '}],
[["C_r" , 16],'Question', {q:' Online-Vorlesung - Kamera '}],
[["C_u" , 16],'Question', {q:' Online-Vorlesung - Teekanne '}],
[["C_r" , 17],'Question', {q:' Schwimmen - Freibad '}],
[["C_u" , 17],'Question', {q:' Schwimmen - Park '}],
[["C_r" , 18],'Question', {q:' Füttern - Dose '}],
[["C_u" , 18],'Question', {q:' Füttern - Zeitung '}],
[["C_r" , 19],'Question', {q:' Fitnessstudio - Laufband '}],
[["C_u" , 19],'Question', {q:' Fitnessstudio - Heimweg '}],
[["C_r" , 20],'Question', {q:' Regen - Schirm '}],
[["C_u" , 20],'Question', {q:' Regen - Schrank '}],
[["C_r" , 21],'Question', {q:' Schuhe - Dreck '}],
[["C_u" , 21],'Question', {q:' Schuhe - Stolz '}],
[["C_r" , 22],'Question', {q:' Nachhilfe - Lehrmaterial '}],
[["C_u" , 22],'Question', {q:' Nachhilfe - Spielzeug '}],
[["C_r" , 23],'Question', {q:' Vorstellung - Vorhang '}],
[["C_u" , 23],'Question', {q:' Vorstellung - Eingang '}],
[["C_r" , 24],'Question', {q:' Tiere - Heim '}],
[["C_u" , 24],'Question', {q:' Tiere - Imbiss '}],
[["C_r" , 25],'Question', {q:' Pflanze - Topf '}],
[["C_u" , 25],'Question', {q:' Pflanze - Buch '}],
[["C_r" , 26],'Question', {q:' Kälte - Heizung '}],
[["C_u" , 26],'Question', {q:' Kälte - Shorts '}],
[["C_r" , 27],'Question', {q:' Laufen - Marathon '}],
[["C_u" , 27],'Question', {q:' Laufen - Kochkurs '}],
[["C_r" , 28],'Question', {q:' Lesen - Bibliothek '}],
[["C_u" , 28],'Question', {q:' Lesen - Spielhalle '}],
[["C_r" , 29],'Question', {q:' Sprinten - Verschwitzten '}],
[["C_u" , 29],'Question', {q:' Sprinten - Gedankenverloren '}],
[["C_r" , 30],'Question', {q:' Sushi - Japaner '}],
[["C_u" , 30],'Question', {q:' Sushi - Verwandten '}],
[["C_r" , 31],'Question', {q:' Bratkartoffeln - Pflanzenöl '}],
[["C_u" , 31],'Question', {q:' Bratkartoffeln - Spülmittel '}],
[["C_r" , 32],'Question', {q:' Putzen - Staubsauger '}],
[["C_u" , 32],'Question', {q:' Putzen - Fernbedienung '}],
[["C_r" , 33],'Question', {q:' Bad - Lavendelöl '}],
[["C_u" , 33],'Question', {q:' Bad - Reinigungsmittel '}],
[["C_r" , 34],'Question', {q:' Musikkonzert - Klavier '}],
[["C_u" , 34],'Question', {q:' Musikkonzert - Fernseher '}],
[["C_r" , 35],'Question', {q:' Rede - Podium '}],
[["C_u" , 35],'Question', {q:' Rede - Toilette '}],
[["C_r" , 36],'Question', {q:' Obst - Apfel '}],
[["C_u" , 36],'Question', {q:' Obst - Kleidung '}],
[["C_r" , 37],'Question', {q:' Verreisen - Zugticket '}],
[["C_u" , 37],'Question', {q:' Verreisen - Fernseher '}],
[["C_r" , 38],'Question', {q:' Motorrad - Helm '}],
[["C_u" , 38],'Question', {q:' Motorrad - Laufjacke '}],
[["C_r" , 39],'Question', {q:' Shoppen - Einkaufszentrum '}],
[["C_u" , 39],'Question', {q:' Shoppen - Tannenwald '}],
[["C_r" , 40],'Question', {q:' Salat - Spinat '}],
[["C_u" , 40],'Question', {q:' Salat - Besen '}],
[["C_r" , 41],'Question', {q:' Versammlung - Familienessen '}],
[["C_u" , 41],'Question', {q:' Versammlung - Fallschirmsprung '}],
[["C_r" , 42],'Question', {q:' Lernen - Kurs '}],
[["C_u" , 42],'Question', {q:' Lernen - Party '}],
[["C_r" , 43],'Question', {q:' Weihnachten - Nikolaus '}],
[["C_u" , 43],'Question', {q:' Weihnachten - Sensenmann '}],
[["C_r" , 44],'Question', {q:' Job - Beförderung '}],
[["C_u" , 44],'Question', {q:' Job - Schulterklopfer '}],
[["C_r" , 45],'Question', {q:' Glücksspiel - Casino '}],
[["C_u" , 45],'Question', {q:' Glücksspiel - Kunstgalerie '}],
[["C_r" , 46],'Question', {q:' Strategieren - Schach '}],
[["C_u" , 46],'Question', {q:' Strategieren - Bowling '}],
[["C_r" , 47],'Question', {q:' Kampfsport - Turnier '}],
[["C_u" , 47],'Question', {q:' Kampfsport - Talentshow '}],
[["C_r" , 48],'Question', {q:' Fleisch - BBQ '}],
[["C_u" , 48],'Question', {q:' Fleisch - Proteste '}],
[["C_r" , 49],'Question', {q:' Netzwerk - Online-Profil '}],
[["C_u" , 49],'Question', {q:' Netzwerk - Sportteam '}],
[["C_r" , 50],'Question', {q:' Schauspielerin - Rollen '}],
[["C_u" , 50],'Question', {q:' Schauspielerin - Geschenke '}],
[["C_r" , 51],'Question', {q:' Vorstellungsgespräch - Lebenslauf '}],
[["C_u" , 51],'Question', {q:' Vorstellungsgespräch - Auftritt '}],
[["C_r" , 52],'Question', {q:' Tischler - Sägen '}],
[["C_u" , 52],'Question', {q:' Tischler - Stoff '}],
[["C_r" , 53],'Question', {q:' Kind - Schule '}],
[["C_u" , 53],'Question', {q:' Kind - Praxis '}],
[["C_r" , 54],'Question', {q:' Malen - Pinsel '}],
[["C_u" , 54],'Question', {q:' Malen - Zeitung '}],
[["C_r" , 55],'Question', {q:' Party - Snackschale '}],
[["C_u" , 55],'Question', {q:' Party - Tischläufer '}],
[["C_r" , 56],'Question', {q:' Segeln - Mehrrumpfboot '}],
[["C_u" , 56],'Question', {q:' Segeln - Hautschutzcreme '}],
[["C_r" , 57],'Question', {q:' Frühstück - Marmeladenglas '}],
[["C_u" , 57],'Question', {q:' Frühstück - Katzenfutter '}],
[["C_r" , 58],'Question', {q:' Elefant - Tierbaby '}],
[["C_u" , 58],'Question', {q:' Elefant - Kind '}],
[["C_r" , 59],'Question', {q:' Gottesdienst - Kerze '}],
[["C_u" , 59],'Question', {q:' Gottesdienst - Zigarette '}],
[["C_r" , 60],'Question', {q:' Bibliothek - Lesesaal '}],
[["C_u" , 60],'Question', {q:' Bibliothek - Speisesaal '}],
[["C_r" , 61],'Question', {q:' Film - 3D-Brille '}],
[["C_u" , 61],'Question', {q:' Film - Pyjamas '}],
[["C_r" , 62],'Question', {q:' Lohnzuschlag - Einzahlung '}],
[["C_u" , 62],'Question', {q:' Lohnzuschlag - Reise '}],
[["C_r" , 63],'Question', {q:' Projektgruppe - Studie '}],
[["C_u" , 63],'Question', {q:' Projektgruppe - Konferenz '}],
[["C_r" , 64],'Question', {q:' Hochzeitstermin - Vorbereitung '}],
[["C_u" , 64],'Question', {q:' Hochzeitstermin - Karriere '}],
[["C_r" , 65],'Question', {q:' Duschen - Wasserhahn '}],
[["C_u" , 65],'Question', {q:' Duschen - Herd '}],
[["C_r" , 66],'Question', {q:' Theater - Ticket '}],
[["C_u" , 66],'Question', {q:' Theater - Pizza '}],
[["C_r" , 67],'Question', {q:' Mojito - Limette '}],
[["C_u" , 67],'Question', {q:' Mojito - Rührei '}],
[["C_r" , 68],'Question', {q:' Malen - Pinsel '}],
[["C_u" , 68],'Question', {q:' Malen - Picknickkorb '}],
[["C_r" , 69],'Question', {q:' Sportwagen - Rennkarten '}],
[["C_u" , 69],'Question', {q:' Sportwagen - Rätselbuch '}],
[["C_r" , 70],'Question', {q:' Geige - Notenheft '}],
[["C_u" , 70],'Question', {q:' Geige - Kamera '}],
[["C_r" , 71],'Question', {q:' Hund - Leine '}],
[["C_u" , 71],'Question', {q:' Hund - Autoschlüssel '}],
[["C_r" , 72],'Question', {q:' Restaurant - Bar '}],
[["C_u" , 72],'Question', {q:' Restaurant - Schwimmbad '}],
[["C_r" , 73],'Question', {q:' Tochter - ABC-Buch '}],
[["C_u" , 73],'Question', {q:' Tochter - Weinglas '}],
[["C_r" , 74],'Question', {q:' Halsschmerzen - Medikament '}],
[["C_u" , 74],'Question', {q:' Halsschmerzen - Kissen '}],
[["C_r" , 75],'Question', {q:' Spiel - Kneipe '}],
[["C_u" , 75],'Question', {q:' Spiel - Trainieren '}],
[["C_r" , 76],'Question', {q:' Tee - Honig '}],
[["C_u" , 76],'Question', {q:' Tee - Buch '}],
[["C_r" , 77],'Question', {q:' Auto - Linienbus '}],
[["C_u" , 77],'Question', {q:' Auto - Papierkram '}],
[["C_r" , 78],'Question', {q:' Brief - Stift '}],
[["C_u" , 78],'Question', {q:' Brief - Yogamatte '}],
[["C_r" , 79],'Question', {q:' Spielen - Spielsache '}],
[["C_u" , 79],'Question', {q:' Spielen - Snack '}],
[["C_r" , 80],'Question', {q:' Brettspiel - Anleitung '}],
[["C_u" , 80],'Question', {q:' Brettspiel - Kochrezept '}],
[["C_r" , 81],'Question', {q:' Reparieren - Werkzeug '}],
[["C_u" , 81],'Question', {q:' Reparieren - Geschenk '}],
[["C_r" , 82],'Question', {q:' Prüfung - Lehrbuch '}],
[["C_u" , 82],'Question', {q:' Prüfung - Kleiderschrank '}],
[["C_r" , 83],'Question', {q:' Blume - Erde '}],
[["C_u" , 83],'Question', {q:' Blume - Auto '}],
[["C_r" , 84],'Question', {q:' Hausaufgabe - Schulbuch '}],
[["C_u" , 84],'Question', {q:' Hausaufgabe - Hausschlüssel '}],
[["C_r" , 85],'Question', {q:' Prüfung - Note '}],
[["C_u" , 85],'Question', {q:' Prüfung - Partygeschicht '}],
[["C_r" , 86],'Question', {q:' Planet - Teleskop '}],
[["C_u" , 86],'Question', {q:' Planet - Tischtennisplatte '}],
[["C_r" , 87],'Question', {q:' Tennismatch - Umkleidekabine '}],
[["C_u" , 87],'Question', {q:' Tennismatch - Familien '}],
[["C_r" , 88],'Question', {q:' Zahnschmerzen - Schmerzmittel '}],
[["C_u" , 88],'Question', {q:' Zahnschmerzen - Sommerkleidung '}],
[["C_r" , 89],'Question', {q:' Shoppen - Schaufenster '}],
[["C_u" , 89],'Question', {q:' Shoppen - Speisekammer '}],
[["C_r" , 90],'Question', {q:' Wahrsagerin - Handlesen '}],
[["C_u" , 90],'Question', {q:' Wahrsagerin - Kuchenstück '}],
[["C_r" , 91],'Question', {q:' Fahrprüfung - Führerschein '}],
[["C_u" , 91],'Question', {q:' Fahrprüfung - Geschenk '}],
[["V_r" , 100],'Question', {q:' Boutique - Hose '}],
[["V_u" , 100],'Question', {q:' Boutique - Τaxi '}],
[["V_r" , 101],'Question', {q:' Bäckerei - Brötchen '}],
[["V_u" , 101],'Question', {q:' Bäckerei - Ticket '}],
[["V_r" , 102],'Question', {q:' Toilette - Kabine '}],
[["V_u" , 102],'Question', {q:' Toilette - Mensa '}],
[["V_r" , 103],'Question', {q:' Café - Getränk '}],
[["V_u" , 103],'Question', {q:' Café - Schrank '}],
[["V_r" , 104],'Question', {q:' Gartenmarkt - Blume '}],
[["V_u" , 104],'Question', {q:' Gartenmarkt - Haar '}],
[["V_r" , 105],'Question', {q:' Fitnessstudio - Laufband '}],
[["V_u" , 105],'Question', {q:' Fitnessstudio - Tiefgarage '}],
[["V_r" , 106],'Question', {q:' Obst - Salat '}],
[["V_u" , 106],'Question', {q:' Obst - Ärger '}],
[["V_r" , 107],'Question', {q:' Fleischerei - Wurst '}],
[["V_u" , 107],'Question', {q:' Fleischerei - Hemd '}],
[["V_r" , 108],'Question', {q:' See - Schwimmweste '}],
[["V_u" , 108],'Question', {q:' See - Sicherheitsgurt '}],
[["V_r" , 109],'Question', {q:' Badewanne - Seife '}],
[["V_u" , 109],'Question', {q:' Badewanne - T-shirt '}],
[["V_r" , 110],'Question', {q:' Geburtstagparty - Torte '}],
[["V_u" , 110],'Question', {q:' Geburtstagparty - Steak '}],
[["V_r" , 111],'Question', {q:' Gewitter - Regenschirm '}],
[["V_u" , 111],'Question', {q:' Gewitter - Kleiderschrank '}],
[["V_r" , 112],'Question', {q:' Kälte - Schneefall '}],
[["V_u" , 112],'Question', {q:' Kälte - Sperling '}],
[["V_r" , 113],'Question', {q:' Bank - Geldautomat '}],
[["V_u" , 113],'Question', {q:' Bank - Wasserspender '}],
[["V_r" , 114],'Question', {q:' Schule - Lehrer '}],
[["V_u" , 114],'Question', {q:' Schule - Mutter '}],
[["V_r" , 115],'Question', {q:' Museum - Statue '}],
[["V_u" , 115],'Question', {q:' Museum - Ampel '}],
[["V_r" , 116],'Question', {q:' Konzert - Sängerin '}],
[["V_u" , 116],'Question', {q:' Konzert - Allee '}],
[["V_r" , 117],'Question', {q:' Hütte - Wand '}],
[["V_u" , 117],'Question', {q:' Hütte - Rest '}],
[["V_r" , 118],'Question', {q:' Mensa - Eßtisch '}],
[["V_u" , 118],'Question', {q:' Mensa - Moped '}],
[["V_r" , 119],'Question', {q:' Universität - Professor '}],
[["V_u" , 119],'Question', {q:' Universität - Bruder '}],
[["V_r" , 120],'Question', {q:' Übernachtungsparty - Nachthemd '}],
[["V_u" , 120],'Question', {q:' Übernachtungsparty - Regenmantel '}],
[["V_r" , 121],'Question', {q:' Autohaus - Berater '}],
[["V_u" , 121],'Question', {q:' Autohaus - Nachbar '}],
[["V_r" , 122],'Question', {q:' Führerschein - Auto '}],
[["V_u" , 122],'Question', {q:' Führerschein - Fahrrad '}],
[["V_r" , 123],'Question', {q:' Picknick - Korb '}],
[["V_u" , 123],'Question', {q:' Picknick - Herd '}],
[["V_r" , 124],'Question', {q:' Wanne - Seife '}],
[["V_u" , 124],'Question', {q:' Sohn - Sock '}],
[["V_r" , 125],'Question', {q:' Postamt - Paket '}],
[["V_u" , 125],'Question', {q:' Postamt - Taxi '}],
[["V_r" , 126],'Question', {q:' Geschäftstreffen - Hoseanzug '}],
[["V_u" , 126],'Question', {q:' Geschäftstreffen - Slipper '}],
[["V_r" , 127],'Question', {q:' Bahnticket - Bahngleis '}],
[["V_u" , 127],'Question', {q:' Bahnticket - Theaterplatz '}],
[["V_r" , 128],'Question', {q:' Geburtstagstorte - Mixer '}],
[["V_u" , 128],'Question', {q:' Geburtstagstorte - Wanne '}],
[["V_r" , 129],'Question', {q:' Fußballticket - Wettkampf '}],
[["V_u" , 129],'Question', {q:' Fußballticket - Speisesaal '}],
[["V_r" , 130],'Question', {q:' Apotheke - Vitamine '}],
[["V_u" , 130],'Question', {q:' Apotheke - Rotwein '}],
[["V_r" , 131],'Question', {q:' Laden - Handtasche '}],
[["V_u" , 131],'Question', {q:' Laden - Kinderwagen '}],
[["V_r" , 132],'Question', {q:' Kleid - Fäden '}],
[["V_u" , 132],'Question', {q:' Kleid - Schere '}],
[["V_r" , 133],'Question', {q:' Hausschlüssel - Angst '}],
[["V_u" , 133],'Question', {q:' Hausschlüssel - Glück '}],
[["V_r" , 134],'Question', {q:' Katze - Napf '}],
[["V_u" , 134],'Question', {q:' Katze - Kanne '}],
[["V_r" , 135],'Question', {q:' Sportsgeschäft - Fußball '}],
[["V_u" , 135],'Question', {q:' Sportsgeschäft - Kaffee '}],
[["V_r" , 136],'Question', {q:' Tatort - Leichnam '}],
[["V_u" , 136],'Question', {q:' Tatort - Begutachtung '}],
[["V_r" , 137],'Question', {q:' Tiergehege - Hunde '}],
[["V_u" , 137],'Question', {q:' Tiergehege - Haus '}],
[["V_r" , 138],'Question', {q:' Tiergeschäft - Halsband '}],
[["V_u" , 138],'Question', {q:' Tiergeschäft - Sonnenbrille '}],
[["V_r" , 139],'Question', {q:' Buchhandlung - Krimi '}],
[["V_u" , 139],'Question', {q:' Buchhandlung - Orange '}],
[["V_r" , 140],'Question', {q:' Apotheke - Salbe '}],
[["V_u" , 140],'Question', {q:' Apotheke - Döner '}],
[["V_r" , 141],'Question', {q:' Bäckerei - Croissant '}],
[["V_u" , 141],'Question', {q:' Bäckerei - Tasche '}],
[["V_r" , 142],'Question', {q:' Stadion - Tribüne '}],
[["V_u" , 142],'Question', {q:' Stadion - Roller '}],
[["V_r" , 143],'Question', {q:' Kiosk - Kalender '}],
[["V_u" , 143],'Question', {q:' Kiosk - Pfanne '}],
[["V_r" , 144],'Question', {q:' Frühstuck - Eierkocher '}],
[["V_u" , 144],'Question', {q:' Frühstuck - Geschirrspüler '}],
[["V_r" , 145],'Question', {q:' Hotel - Concierge '}],
[["V_u" , 145],'Question', {q:' Hotel - Ohrenarzt '}],
[["V_r" , 146],'Question', {q:' Arztpraxis - Krankenschwester '}],
[["V_u" , 146],'Question', {q:' Arztpraxis - Abteilungsleiter '}],
[["V_r" , 147],'Question', {q:' Theater - Loge '}],
[["V_u" , 147],'Question', {q:' Theater - Moped '}],
[["V_r" , 148],'Question', {q:' Kirche - Kerze '}],
[["V_u" , 148],'Question', {q:' Kirche - Wolke '}],
[["V_r" , 149],'Question', {q:' Spa - Kopfmassage '}],
[["V_u" , 149],'Question', {q:' Spa - Blumenstrauß '}],
[["V_r" , 150],'Question', {q:' Reitschule - Pferdesattel '}],
[["V_u" , 150],'Question', {q:' Reitschule - Fahrradhelm '}],
[["V_r" , 151],'Question', {q:' Feuerwehreinsatz - Gummischlauch '}],
[["V_u" , 151],'Question', {q:' Feuerwehreinsatz - Brückentag '}],
[["V_r" , 152],'Question', {q:' Fußballspiel - Eigentor '}],
[["V_u" , 152],'Question', {q:' Fußballspiel - Abwärmen '}],
[["V_r" , 153],'Question', {q:' Postkarte - Briefkasten '}],
[["V_u" , 153],'Question', {q:' Postkarte - Geldbeutel '}],
[["V_r" , 154],'Question', {q:' Gurke - Salat '}],
[["V_u" , 154],'Question', {q:' Gurke - Kuchen '}],
[["V_r" , 155],'Question', {q:' Vase - Gefäß '}],
[["V_u" , 155],'Question', {q:' Vase - Überrest '}],
[["V_r" , 156],'Question', {q:' Hörsaal - Tafel '}],
[["V_u" , 156],'Question', {q:' Hörsaal - Mensa '}],
[["V_r" , 157],'Question', {q:' Dokument - Papier '}],
[["V_u" , 157],'Question', {q:' Dokument - Rest '}],
[["V_r" , 158],'Question', {q:' Jura - Anwalt '}],
[["V_u" , 158],'Question', {q:' Jura - Berater '}],
[["V_r" , 159],'Question', {q:' Berg - Klippe '}],
[["V_u" , 159],'Question', {q:' Berg - Laterne '}],
[["V_r" , 160],'Question', {q:' Tablette - Medizin '}],
[["V_u" , 160],'Question', {q:' Tablette - Rechnung '}],
[["V_r" , 161],'Question', {q:' Ordner - Akt '}],
[["V_u" , 161],'Question', {q:' Ordner - Rest '}],
[["V_r" , 162],'Question', {q:' Krankenhaus - Werkzeug '}],
[["V_u" , 162],'Question', {q:' Krankenhaus - Toilette '}],
[["V_r" , 163],'Question', {q:' Strafzettel - Rechnung '}],
[["V_u" , 163],'Question', {q:' Strafzettel - Steuern '}],
[["V_r" , 164],'Question', {q:' Tanzschule - Lehrer '}],
[["V_u" , 164],'Question', {q:' Tanzschule - Arzt '}],
[["V_r" , 165],'Question', {q:' Bauer - Ei '}],
[["V_u" , 165],'Question', {q:' Bauer - Schuh '}],
[["V_r" , 166],'Question', {q:' Experiment - Labor '}],
[["V_u" , 166],'Question', {q:' Experiment - Empfang '}],
[["V_r" , 167],'Question', {q:' Trompete - Instrument '}],
[["V_u" , 167],'Question', {q:' Tropmete - Werkzeug '}],
[["V_r" , 168],'Question', {q:' Supermarkt - Kunde '}],
[["V_u" , 168],'Question', {q:' Supermarkt - Freund '}],
[["V_r" , 169],'Question', {q:' Post - Schalter '}],
[["V_u" , 169],'Question', {q:' Post - Fahrplan '}],
[["V_r" , 170],'Question', {q:' Schicht - Mittagspause '}],
[["V_u" , 170],'Question', {q:' Schicht - Feierabend '}],
[["V_r" , 171],'Question', {q:' Werkstatt - Berater '}],
[["V_u" , 171],'Question', {q:' Werkstatt - Rechtsanwalt '}],
[["C_r" , 200],'Question', {q:' Malen - Pinsel '}],
[["B_r" , 201],'Question', {q:' Fitnesstudio - Laufband '}]

];
